import dynamic from 'dva/dynamic';

// wrapper of dynamic
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  models: () => models.map(m => import(`../models/${m}.js`)),
  component,
});

// nav data
export const getNavData = app => [
  {
    component: dynamicWrapper(app, ['messageInfo', 'seeMedia'], () => import('../layouts/BasicLayout')),
    layout: 'BasicLayout',
    name: '首页', // for breadcrumb
    path: '/',
    children: [
      {
        name: '首页',
        icon: 'dashboard',
        path: 'home',
        isHide: true,
        children: [
          {
            name: '管网首页',
            path: 'pipe-net',
            isHide: true,
            component: dynamicWrapper(app, ['homePage', 'eventList'], () => import('../routes/HomePage/homePage')),
          },
          {
            name: '调度主任首页',
            path: 'director',
            isHide: true,
            component: dynamicWrapper(app, ['homePage'], () => import('../routes/HomePage/dispatcherPage')),
          },
          {
            name: '设备首页',
            path: 'equipment',
            isHide: true,
            component: dynamicWrapper(app, ['homePage'], () => import('../routes/HomePage/equipmentPage')),
          },
          {
            name: '场站首页',
            path: 'station',
            isHide: true,
            component: dynamicWrapper(app, [], () => import('../routes/Station/OperationPlan/OperationPlan')),
          },
          {
            name: '建设中',
            path: 'building',
            isHide: true,
            component: dynamicWrapper(app, [], () => import('../routes/HomePage/building')),
          },
        ],
      },
      {
        name: '消息列表',
        icon: 'dashboard',
        path: 'message-list',
        isHide: true,
        component: dynamicWrapper(app, [], () => import('../routes/MessageList/MessageList')),
        children: [
        ],
      },
      {
        name: '待办箱',
        icon: 'calendar',
        path: 'todo',
        component: null,
        children: [],
      },
      {
        name: '工单中心',
        icon: 'profile',
        path: 'workOrder-list',
        component: dynamicWrapper(app, ['eventList', 'workOrder', 'seeMedia', 'patrolPlanList'], () => import('../routes/WorkOrderManage/workOrderOverview/workOrderOverview')),
        children: [],
      },
      {
        name: '碰接置换工单中心',
        icon: 'profile',
        path: 'bump-replacement-list',
        component: dynamicWrapper(app, ['eventList', 'workOrder', 'seeMedia', 'patrolPlanList', 'thirdWorkOrder'], () => import('../routes/WorkOrderManage/BumpReplacementList')),
        children: [],
      },
      {
        name: '第三方施工总览',
        icon: 'profile',
        path: 'third-workOrder-list',
        component: dynamicWrapper(app, ['eventList', 'thirdWorkOrder', 'seeMedia', 'patrolPlanList'], () => import('../routes/WorkOrderManage/thirdWorkOrderList/thirdWorkOrderList')),
        children: [],
      },
      {
        name: '地图展示',
        icon: 'picture',
        path: 'mapView',
        component: dynamicWrapper(app, ['mapView', 'thematicStatistics', 'patrolTrace'], () => import('../routes/MapView/MapView')),
        children: [],
      },
      {
        name: '碰接置换',
        icon: 'profile',
        path: 'collision-replace-list',
        component: dynamicWrapper(app, ['collisionReplace', 'seeMedia'], () => import('../routes/CollisionReplaceManage/CollisionReplaceList/CollisionReplaceList')),
        children: [],
      },
      {
        name: '危险作业',
        icon: 'profile',
        path: 'report-dangerwork-list',
        component: dynamicWrapper(app, ['eventList', 'thirdWorkOrder', 'seeMedia', 'patrolPlanList', 'dangerWork'], () => import('../routes/DangerWork/WorkList')),
        children: [],
      },
      {
        name: '工单管理',
        icon: 'profile',
        path: 'order',
        isHide: true,
        children: [
          {
            name: '工单详情',
            path: 'workOrder-list-detail',
            isHide: true,
            component: dynamicWrapper(app, ['workOrder', 'seeMedia', 'service'], () => import('../routes/WorkOrderManage/workOrderDetail/workOrderDetail')),
          },
        ],
      },
      {
        name: '日志',
        icon: 'profile',
        path: 'log',
        children: [
          {
            name: '登录日志',
            path: 'login-log',
            component: dynamicWrapper(app, ['loginLog'], () => import('../routes/Log/LoginLog/LoginLog')),
          },
          {
            name: '在线人数统计',
            path: 'count-people',
            component: dynamicWrapper(app, ['countPeople'], () => import('../routes/Log/CountPeople/CountPeople')),
          },
        ],
      },
      {
        name: '输配管理',
        icon: 'shake',
        path: 'distribution',
        children: [
          {
            name: '月计划上报',
            path: 'month-list',
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/MonthReport/MonthList')),
          },
          {
            name: '月计划上报详情',
            path: 'monthDetail',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/MonthReport/MonthDetail')),
          },
          {
            name: '月计划上报表单',
            path: 'monthReport',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/MonthReport/MonthReport')),
          },
          {
            name: '月计划上报修改',
            path: 'monthUpdate',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/MonthReport/MonthUpdate')),
          },
          {
            name: '周计划上报',
            path: 'week-list',
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/WeekReport/WeekList')),
          },
          {
            name: '周计划上报详情',
            path: 'weekDetail',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/WeekReport/WeekDetail')),
          },
          {
            name: '周计划上报表单',
            path: 'weekReport',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/WeekReport/WeekReport')),
          },
          {
            name: '周计划上报修改',
            path: 'weekUpdate',
            isHide: true,
            component: dynamicWrapper(app, ['report'], () => import('../routes/Distribution/WeekReport/WeekUpdate')),
          },
          {
            name: '月计划制定',
            path: 'monthPlan',
            component: dynamicWrapper(app, ['make'], () => import('../routes/Distribution/MakePlan/MonthPlan')),
          },
          {
            name: '月计划制定详情',
            path: 'makeDetail',
            isHide: true,
            component: dynamicWrapper(app, ['make'], () => import('../routes/Distribution/MakePlan/MakeDetail')),
          },
          {
            name: '月计划制定表单',
            path: 'makeMonth',
            isHide: true,
            component: dynamicWrapper(app, ['make'], () => import('../routes/Distribution/MakePlan/MakeMonth')),
          },
          {
            name: '月计划制定修改',
            path: 'makeMonthUpdate',
            isHide: true,
            component: dynamicWrapper(app, ['make'], () => import('../routes/Distribution/MakePlan/MakeMonthUpdate')),
          },
          {
            name: '周计划制定',
            path: 'weekPlan',
            component: dynamicWrapper(app, ['weekMake'], () => import('../routes/Distribution/WeekMake/WeekPlan')),
          },
          {
            name: '周计划制定详情',
            path: 'makeWeekDetail',
            isHide: true,
            component: dynamicWrapper(app, ['weekMake'], () => import('../routes/Distribution/WeekMake/MakeDetail')),
          },
          {
            name: '周计划制定表单',
            path: 'makeWeek',
            isHide: true,
            component: dynamicWrapper(app, ['weekMake'], () => import('../routes/Distribution/WeekMake/MakeWeek')),
          },
          {
            name: '周计划制定修改',
            path: 'makeWeekUpdate',
            isHide: true,
            component: dynamicWrapper(app, ['weekMake'], () => import('../routes/Distribution/WeekMake/MakeWeekUpdate')),
          },
          {
            name: '气量统计',
            path: 'volume-static',
            component: dynamicWrapper(app, [], () => import('../routes/BlackPage/BlackPage')),
          },
          {
            name: '气量分析',
            path: 'volume-anal',
            component: dynamicWrapper(app, [], () => import('../routes/BlackPage/BlackPage')),
          },
          {
            name: '管网监测',
            path: 'monitor',
            component: dynamicWrapper(app, ['monitor'], () => import('../routes/Monitor/Monitor')),
          },
          {
            name: '管网监测卡片',
            path: 'monitor-card',
            component: dynamicWrapper(app, ['monitor'], () => import('../routes/MonitorList/MonitorList')),
          },
        ],
      },
      {
        name: '事件管理',
        icon: 'exception',
        path: 'event-list',
        component: dynamicWrapper(app, ['eventList', 'patrolPlanList'], () => import('../routes/EventManage/eventOverview/eventOverview')),
        children: [],
      },
      {
        name: '事件详情',
        path: 'event-list-detail',
        isHide: true,
        component: dynamicWrapper(app, ['eventList', 'seeMedia'], () => import('../routes/EventManage/eventDetail/eventDetail')),
      },
      {
        name: '管网运行',
        icon: 'dashboard',
        path: 'query',
        children: [
          {
            name: '区域管理',
            path: 'regional-manage',
            isHide: false,
            component: dynamicWrapper(app, ['regionalManage', 'patrolTrace'], () => import('../routes/regionalManage/RegionalManage')),
          },
          {
            name: '区域边缘捕捉',
            path: 'regional-edite',
            isHide: false,
            component: dynamicWrapper(app, [], () => import('../routes/regionalManage/editArea')),
          },
          {
            name: '管控日报统计',
            path: 'workOrder-report-count',
            component: dynamicWrapper(app, ['reportCount'], () => import('../routes/ReportCount/ReportCount')),
          },
          {
            name: '第三方施工分析',
            path: 'third-construction',
            isHide: false,
            component: dynamicWrapper(app, ['statistics'], () => import('../routes/Report/ThirdConstruction')),
          },
          {
            name: '第三方施工分析',
            path: 'third-construction-promotion',
            isHide: false,
            component: dynamicWrapper(app, ['statistics'], () => import('../routes/Report/ThirdConstructionPromotion')),
          },
          {
            name: '计划制定',
            path: 'patrol-plan-list',
            component: dynamicWrapper(app, ['patrolPlanList'], () => import('../routes/PlanEnact/P_PatrolPlan')),
          },
          {
            name: '任务总览',
            path: 'patrol-task-list',
            component: dynamicWrapper(app, ['patrolPlanList', 'patrolTaskList'], () => import('../routes/TaskLook/T_PatrolPlan')),
          },
          {
            name: '巡线任务分析',
            path: 'keyPoint-inspection',
            isHide: false,
            component: dynamicWrapper(app, ['statistics', 'regionalManage', 'patrolTaskList'], () => import('../routes/Report/KeyPointInsp')),
          },
          {
            name: '巡线任务分析（原生产）',
            path: 'keyPoint-inspection-oldpro',
            isHide: false,
            component: dynamicWrapper(app, ['statistics', 'regionalManage', 'patrolTaskList'], () => import('../routes/Report/KeyPointInspOldpro')),
          },
          {
            name: '人员位置',
            path: 'patrol-trace',
            isHide: false,
            component: dynamicWrapper(app, ['patrolTrace'], () => import('../routes/positionAndTrace/ShowPatrolPerson')),
          },
          {
            name: '巡视计划制定',
            path: 'patrol-plan-s',
            component: dynamicWrapper(app, ['maintain', 'patrolPlanList'], () => import('../routes/PatrolS/PatrolSPlan')),
          },
          {
            name: '巡视计划添加',
            path: 'patrolS-plan-add',
            isHide: true,
            component: dynamicWrapper(app, ['patrolPlanList'], () => import('../routes/PatrolS/Form/planTemplate')),
          },
          {
            name: '巡视计划编辑',
            path: 'patrolS-plan-edit',
            isHide: true,
            component: dynamicWrapper(app, ['patrolPlanList'], () => import('../routes/PatrolS/Form/planEditplate')),
          },
          {
            name: '碰接置换',
            path: 'collision',
            isHide: false,
            component: null,
          },
          {
            name: '作业计划制定',
            path: 'plan-list',
            component: dynamicWrapper(app, ['maintain', 'taskdetail'], () => import('../routes/Maintain/Maintenance')),
          },
          {
            name: '作业任务总览',
            path: 'task-summary',
            component: dynamicWrapper(app, ['maintain', 'seeMedia'], () => import('../routes/Maintain/TaskSummary')),
          },
          {
            name: '作业任务分析',
            path: 'maintain-task',
            isHide: false,
            component: dynamicWrapper(app, ['statistics'], () => import('../routes/Report/MaintainTtask')),
          },
          {
            name: '单个任务',
            path: 'task-one',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/TaskOne')),
          },
          {
            name: '任务详情',
            path: 'task-detail',
            isHide: true,
            component: dynamicWrapper(app, ['taskdetail', 'seeMedia', 'patrolTrace'], () => import('../routes/Maintain/TaskDetail')),
          },
          {
            name: '养护详情',
            path: 'valve-detail',
            isHide: true,
            component: dynamicWrapper(app, ['taskdetail'], () => import('../routes/Maintain/ValveDetail')),
          },
          {
            name: '巡线计划添加',
            path: 'patrol-plan-add',
            isHide: true,
            component: dynamicWrapper(app, ['patrolPlanList'], () => import('../routes/Form/planTemplate')),
          },
          {
            name: '巡线任务详情',
            path: 'patrol-task-detail',
            isHide: true,
            component: dynamicWrapper(app, ['patrolPlanList', 'patrolTrace', 'patrolTaskList'], () => import('../routes/Form/TaskDetail')),
          },
          {
            name: '事件上报表单',
            path: 'report-eventform',
            isHide: true,
            component: dynamicWrapper(app, ['submitFormManage', 'contractNum', 'engineeringCode'], () => import('../routes/submitFormManage/SubmitFormManage')),
          },
          {
            name: '新建危险作业',
            path: 'report-dangerwork',
            isHide: true,
            component: dynamicWrapper(app, ['submitFormManage', 'device', 'dangerWork'], () => import('../routes/DangerWork')),
          },
          {
            name: '危险作业详情',
            path: 'report-dangerwork-detail',
            isHide: true,
            component: dynamicWrapper(app, ['submitFormManage', 'device', 'dangerWork'], () => import('../routes/DangerWork/workDetail')),
          },
          {
            name: '停气列表',
            path: 'stopVolume',
            isHide: false,
            component: dynamicWrapper(app, ['stopVolume'], () => import('../routes/StopVolume/StopVolume')),
          },
          {
            name: '巡检车泄露点',
            isHide: true,
            path: 'leak-task/patrol-car-leak-point',
            component: dynamicWrapper(app, ['patrolLeakPoint', 'patrolTrace'], () => import('../routes/PatrolLeakPoint/PatrolLeakPoint')),
          },
          {
            name: '管网检漏',
            path: 'leak',
            component: dynamicWrapper(app, ['leak'], () => import('../routes/PipeLeak/LeakPlan')),
          },
          {
            name: '检漏任务',
            path: 'leak-task',
            component: dynamicWrapper(app, ['leak'], () => import('../routes/PipeLeak/LeakTaskList')),
          },
          {
            name: '绩效考核',
            path: 'count',
            isHide: false,
            component: dynamicWrapper(app, ['statistics'], () => import('../routes/Report/Count')),
          },
          {
            name: '作业计划功能管理',
            path: 'function-manage',
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage')),
          },
          {
            name: '新建作业计划功能管理',
            path: 'newFunction',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage/newFunction')),
          },
          {
            name: '作业计划子功能管理',
            path: 'function-child',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage/indexChild')),
          },
          {
            name: '新建作业计划功能管理',
            path: 'newChildrenFunction',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage/newChildrenFunction')),
          },
          {
            name: '编辑功能',
            path: 'editFunction',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage/editFunction')),
          },
          {
            name: '编辑表单',
            path: 'editForm',
            isHide: true,
            component: dynamicWrapper(app, ['maintain'], () => import('../routes/Maintain/FunctionManage/editTableForm')),
          },
          {
            name: '作业计划模板配置',
            path: 'function-template',
            component: dynamicWrapper(app, ['maintain', 'station'], () => import('../routes/Maintain/FunctionTemplate')),
          },
          {
            name: '新建作业计划模板',
            path: 'new-function-template',
            isHide: true,
            component: dynamicWrapper(app, ['maintain', 'station'], () => import('../routes/Maintain/FunctionTemplate/newFuncModule')),
          },
          {
            name: '排班管理',
            path: 'workforce-manage',
            component: dynamicWrapper(app, ['maintain', 'station', 'IntelliSche', 'patrolPlanList', 'device'], () => import('../routes/Maintain/WorkforceManage')),
          },
        ],
      },
      {
        name: '工商户管理',
        icon: 'printer',
        path: 'ichmanager',
        children: [
          {
            name: '工商户管理',
            path: 'ichAccount-planManager',
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/IchManager/IcMeterMaintenance')),
          },
          {
            name: '计划详情',
            path: 'plan-read',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '计划编辑',
            path: 'plan-edit',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '计划创建',
            path: 'plan-add',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '任务维护管理',
            path: 'ichAccount-taskManager',
            component: dynamicWrapper(app, ['device', 'workOrder', 'operationStandard'], () => import('../routes/Device/TaskPandect')),
          },
          {
            name: '任务详情',
            path: 'task-detaile',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'seeMedia'], () => import('../routes/Device/TaskDetaile')),
          },
          {
            name: '工商户台账',
            path: 'ichAccount',
            isHide: false,
            component: dynamicWrapper(app, ['ichAccount'], () => import('../routes/IchManager/IchAccount')),
          },
          {
            name: '工商户台账详情',
            path: 'ichAccountDetail',
            isHide: true,
            component: dynamicWrapper(app, ['meterTaskResult', 'ichAccountDetail', 'ichAccount', 'ledger'], () => import('../routes/IchManager/IchAccountDetail/ichAccountDetail')),
          },
          {
            name: '工商户表具台账',
            path: 'ichMeterAccount',
            isHide: false,
            component: dynamicWrapper(app, ['patrolPlanList', 'ichMeterAccount'], () => import('../routes/IchManager/IchMeterAccount/IchMeterAccount')),
          },
          {
            name: '工商户表具详情',
            path: 'ichMeterDetail',
            isHide: true,
            component: dynamicWrapper(app, ['ichMeterAccount'], () => import('../routes/IchManager/IchMeterAccount/IchMeterDetail')),
          },
          {
            name: '工商户抄表结果台账',
            path: 'taskResult-summary',
            component: dynamicWrapper(app, ['meterTaskResult'], () => import('../routes/IchManager/IchMeterTaskResult/MeterTaskResult')),
          },
        ],
      },
      {
        name: '场站运行',
        icon: 'trademark',
        path: 'station',
        children: [
          // {
          //   name: '工单管理 ',
          //   path: 'workCenter',
          //   component: dynamicWrapper(app, ['eventList', 'workOrder', 'seeMedia', 'patrolPlanList'], () => import('../routes/Station/WorkCenterManage/WorkCenter')),
          // },
          {
            name: '工单管理 ',
            path: 'wo-list',
            component: dynamicWrapper(app, ['eventList', 'woPlanManage', 'seeMedia', 'patrolPlanList', 'submitFormManage'], () => import('../routes/PlanWorkorder/WorkorderList/WorkorderList')),
          },
          {
            name: '运行计划',
            path: 'plan',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/PlanList')),
          },
          {
            name: '任务总览',
            path: 'task',
            isHide: false,
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/TaskList')),
          },
          {
            name: '任务反馈',
            path: 'task-feedback',
            isHide: true,
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/TaskFeedback')),
          },
          {
            name: '调压通知',
            path: 'notice',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/NoticeList')),
          },
          {
            name: '添加通知',
            path: 'addnotice',
            isHide: true,
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/AddNotice')),
          },
          {
            name: '调压记录',
            path: 'record',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/AddRecord')),
          },
          {
            name: '调压对象管理',
            path: 'objmanage',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/ObjManage')),
          },
          {
            name: '班次管理',
            path: 'classmanage',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/ClassManage')),
          },
          {
            name: '班组管理',
            path: 'teamManage',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/TeamManage')),
          },
          {
            name: '修改检查项',
            path: 'formSubmit',
            isHide: true,
            component: dynamicWrapper(app, ['stationForm'], () => import('../routes/Station/FormData')),
          },
          {
            name: '区域管理',
            path: 'areaManage',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/AreaManage')),
          },
          {
            name: '设备单元管理',
            path: 'equnit',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/EqUnit')),
          },
          {
            name: '检查对象管理',
            path: 'CheckData',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/CheckData')),
          },
          {
            name: '气质组分',
            path: 'gas-comps',
            component: dynamicWrapper(app, [], () => import('../routes/Station/CheckData')),
            // component: dynamicWrapper(app, [], () => import('../routes/Station/CarAccount')),
          },
          {
            name: '气质组分2',
            path: 'TemperComponent',
            component: dynamicWrapper(app, ['TemperComponent', 'seeMedia'], () => import('../routes/TemperComponent')),
            // component: dynamicWrapper(app, [], () => import('../routes/Station/CarAccount')),
          },
          // {
          //   name: '故障管理',
          //   path: 'CZdefault',
          //   component: dynamicWrapper(app, ['CZManage', 'patrolPlanList'], () => import('../routes/CZEventManage/FaultList')),
          //   children: [],
          // },
          // {
          //   name: '隐患管理',
          //   path: 'CZdanger',
          //   component: dynamicWrapper(app, ['CZManage', 'patrolPlanList'], () => import('../routes/CZEventManage/DangerList')),
          //   children: [],
          // },
          {
            name: '隐患管理',
            path: 'danger-mnmg',
            component: dynamicWrapper(app, ['equipRepair', 'patrolPlanList', 'contractNum'], () => import('../routes/CZEventManage/EquipDangerList')),
            children: [],
          },
          {
            name: '故障管理',
            path: 'fault-mnmg',
            component: dynamicWrapper(app, ['CZManage', 'patrolPlanList'], () => import('../routes/CZEventManage/FaultList')),
            children: [],
          },
          {
            name: '装载车记录',
            path: 'car-account',
            component: dynamicWrapper(app, [], () => import('../routes/Station/CheckData')),
            // component: dynamicWrapper(app, [], () => import('../routes/Station/CarAccount')),
          },
          {
            name: '运行记录',
            path: 'account',
            component: dynamicWrapper(app, [], () => import('../routes/Station/Account')),
          },
          {
            name: '值班日志',
            path: 'dutyLog',
            isHide: false,
            component: dynamicWrapper(app, ['DutyManage'], () => import('../routes/Station/DutyLog/DutyLog')),
          },
          {
            name: '值班日志详情',
            path: 'DutyDetail',
            isHide: true,
            component: dynamicWrapper(app, ['DutyManage'], () => import('../routes/Station/DutyLog/DutyDetail')),
          },
          {
            name: '智能排班',
            path: 'IntelliSche',
            isHide: false,
            component: dynamicWrapper(app, ['IntelliSche'], () => import('../routes/IntelliSche')),
          },
          {
            name: '计划制定',
            path: 'new',
            isHide: true,
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/ModalForm/NewForm')),
          },
          {
            name: '计划查看',
            path: 'plan-detail',
            isHide: true,
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/PlanDetail')),
          },
          {
            name: '任务明细',
            path: 'task-detail',
            component: dynamicWrapper(app, ['station'], () => import('../routes/Station/TaskDetail')),
          },
          {
            name: '加臭记录',
            path: 'Odor-record',
            isHide: false,
            component: dynamicWrapper(app, ['odorization'], () => import('../routes/Station/Odorization')),
          },
          {
            name: '加臭记录详情',
            path: 'Odor-detail',
            isHide: true,
            component: dynamicWrapper(app, ['odorization'], () => import('../routes/Station/Odorization/OdorDetail')),
          },
          {
            name: '加臭记录管理',
            path: 'Odor-manage',
            isHide: false,
            component: dynamicWrapper(app, ['odorization', 'station'], () => import('../routes/Station/Odorization/OdorManage')),
          },
          {
            name: '加臭首页',
            path: 'Odor-index',
            isHide: false,
            component: dynamicWrapper(app, ['odorization', 'station'], () => import('../routes/Station/Odorization/OdorIndex')),
          },
        ],
      },
      {
        name: '工单管理',
        icon: 'code-o',
        path: 'workorderManage',
        isHide: true,
        children: [
          {
            name: '工单策划',
            path: 'wo-plan',
            isHide: true,
            component: dynamicWrapper(app, ['submitFormManage'], () => import('../routes/submitFormManage/SubmitFormManage')),
          },
          {
            name: '工单列表',
            path: 'wo-list',
            isHide: true,
            component: dynamicWrapper(app, ['eventList', 'woPlanManage', 'seeMedia', 'patrolPlanList'], () => import('../routes/PlanWorkorder/WorkorderList/WorkorderList')),
          },
        ],
      },
      {
        name: '隐患管理',
        icon: 'copy',
        path: 'danger-mnmg',
        component: dynamicWrapper(app, ['equipRepair', 'patrolPlanList', 'contractNum'], () => import('../routes/CZEventManage/EquipDangerList')),
        children: [],
      },
      {
        name: '设备管理',
        icon: 'copy',
        path: 'equipment',
        children: [
          {
            name: '工单管理 ',
            path: 'wo-list',
            component: dynamicWrapper(app, ['eventList', 'woPlanManage', 'seeMedia', 'patrolPlanList', 'submitFormManage'], () => import('../routes/PlanWorkorder/WorkorderList/WorkorderList')),
          },
          {
            name: '分类管理',
            path: 'sortmanagement',
            component: dynamicWrapper(app, ['sortmanagement'], () => import('../routes/SortManagement')),
          },
          {
            name: '故障管理',
            path: 'fault-mnmg',
            component: dynamicWrapper(app, ['CZManage', 'patrolPlanList'], () => import('../routes/CZEventManage/FaultList')),
            children: [],
          },
          {
            name: '设备台账',
            path: 'ledger',
            component: dynamicWrapper(app, ['ledger', 'device'], () => import('../routes/Ledger')),
          },
          {
            name: '计划性维护管理',
            path: 'pre-mainten',
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/DeviceMaintenance')),
          },
          {
            name: '计划性维护任务',
            path: 'task-Pandect',
            component: dynamicWrapper(app, ['device', 'workOrder', 'operationStandard'], () => import('../routes/Device/TaskPandect')),
          },
          {
            name: '计划性维护台帐',
            path: 'plan-ledger',
            component: dynamicWrapper(app, ['device', 'planMaintainLedger', 'workOrder', 'operationStandard'], () => import('../routes/Device/PlanMaintainLedger')),
          },
          {
            name: '计划性维护台帐维护历史',
            path: 'maintain-histroy',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'planMaintainLedger', 'workOrder', 'operationStandard'], () => import('../routes/Device/MaintainHistroy')),
          },
          {
            name: '任务详情',
            path: 'task-detaile',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'seeMedia', 'contractNum', 'purNumModal'], () => import('../routes/Device/TaskDetaile')),
          },
          {
            name: '计划性维护详情',
            path: 'plan-read',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '计划性维护编辑',
            path: 'plan-edit',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '计划性维护创建',
            path: 'plan-add',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewRelMaintenPlan')),
          },
          {
            name: '作业标准管理',
            path: 'operation-Manger',
            component: dynamicWrapper(app, ['device', 'operationStandard', 'seeMedia'], () => import('../routes/Device/OperationManger')),
          },
          {
            name: '作业类型管理',
            path: 'operaType-Manger',
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/OperaTypeManger')),
          },
          {
            name: '类型分类管理',
            path: 'operaCater-Manger',
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/OperaCaterManger')),
          },
          {
            name: '新建作业标准',
            path: 'operation-add',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewOperation')),
          },
          {
            name: '新建作业类型',
            path: 'operaType-add',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewOperaType')),
          },
          {
            name: '编辑作业标准',
            path: 'operation-edit',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewOperation')),
          },
          {
            name: '编辑作业类型',
            path: 'operaType-edit',
            isHide: true,
            component: dynamicWrapper(app, ['device', 'operationStandard'], () => import('../routes/Device/NewOperaType')),
          },
          {
            name: '故障体系',
            path: 'malfunction',
            component: dynamicWrapper(app, ['malfunction'], () => import('../routes/Malfunction')),
          },
          {
            name: '位置信息',
            path: 'location',
            component: dynamicWrapper(app, [], () => import('../routes/Location')),
          },
          {
            name: '备品备件',
            path: 'spareParts',
            component: dynamicWrapper(app, ['spareParts'], () => import('../routes/SpareParts/SpareParts')),
          },
          {
            name: '设备监测',
            path: 'monitorList',
            component: dynamicWrapper(app, ['equipmentMonitor', 'station'], () => import('../routes/EquipmentMonitor/MonitorList')),
          },
          {
            name: '设备监测明细',
            path: 'monitorDetail',
            isHide: true,
            component: dynamicWrapper(app, ['equipmentMonitor', 'station', 'device'], () => import('../routes/EquipmentMonitor/MonitorDetail')),
          },
          {
            name: '设备同步',
            path: 'synchronization',
            isHide: true,
            component: dynamicWrapper(app, ['device'], () => import('../routes/Device/EqSynchronization')),
          },
        ],
      },
      {
        name: '应急子页面管理',
        path: 'emergency_childrens',
        isHide: true,
        children: [{
          name: '资源准备情况',
          path: 'resources',
          isHide: true,
          component: dynamicWrapper(app, ['emer', 'emerLfMap'], () => import('../routes/emer/resources')),
        },
        ],
      },
      {
        name: '安全作业',
        icon: 'safety',
        path: 'safe-operation',
        children: [
          {
            name: '加气站',
            path: 'plan',
            isHide: true,
            // component: dynamicWrapper(app, ['station'], () => import('../routes/Station/PlanList')),
          },
          {
            name: '危货运输',
            path: 'task',
            isHide: false,
            component: dynamicWrapper(app, [], () => import('../routes/DangerDoodsTransporte/DangerDoodsTransporte')),
          },
          {
            name: '户内作业',
            path: 'fault',
            isHide: false,
            // component: dynamicWrapper(app, ['eventForm'], () => import('../routes/Station/FaultReport')),
          }],
      },
      {
        name: 'GIS变更台帐',
        icon: 'copy',
        path: 'GIS',
        component: dynamicWrapper(app, ['GisChangeAccount', 'ledger'], () => import('../routes/GisChangeAccount/GisChangeAccount')),
        children: [],
      },
      {
        name: '统计分析',
        icon: 'area-chart',
        isHide: true,
        path: 'report',
        children: [
          {
            name: '巡检工作量',
            path: 'patrol-work',
            isHide: false,
            component: null,
          },
          {
            name: '巡检任务',
            path: 'patrol-task',
            isHide: false,
            component: null,
          },
          {
            name: '停滞点',
            path: 'stop-point',
            isHide: false,
            component: null,
          },
          {
            name: 'GPS日报',
            path: 'gps-log',
            isHide: false,
            component: null,
          },
          {
            name: '带气作业',
            path: 'volume-work',
            isHide: false,
            component: null,
          },
          {
            name: '巡线日志',
            path: 'patrol-log',
            isHide: false,
            component: null,
          },
        ],
      },
      {
        name: '人员评估',
        icon: 'usergroup-delete',
        path: 'assessment',
        children: [
          {
            name: '计分台账',
            path: 'rate-account',
            isHide: false,
            component: null,
          },
          {
            name: '绩效考核',
            path: 'performance',
            isHide: false,
            component: null,
          },
        ],
      },
      {
        name: '系统管理',
        icon: 'setting',
        path: 'system-management',
        children: [
          {
            name: '工单配置',
            path: 'workorder-config',
            component: dynamicWrapper(app, ['workOrderConfig'], () => import('../routes/WorkOrderConfig/WorkOrderConfig')),
          },
          {
            name: '系统全局参数',
            path: 'system-param',
            isHide: false,
            component: dynamicWrapper(app, ['globalParameter'], () => import('../routes/SystemGlobalParameters')),
          },
          {
            name: 'PC&APP地图资源配置',
            path: 'pcapp-mapconfig',
            isHide: false,
            component: dynamicWrapper(app, ['PcAppMapConfig'], () => import('../routes/PcAppMapConfig')),
          },
          {
            name: '积分配置',
            path: 'integral',
            isHide: false,
            component: dynamicWrapper(app, ['integral'], () => import('../routes/Integral')),
          },
          {
            name: '附件管理',
            path: 'attachment-manage',
            isHide: false,
            component: dynamicWrapper(app, ['attachmentManage'], () => import('../routes/AttachmentManage')),
          },
          {
            name: '消息模版配置',
            path: 'message-template',
            isHide: false,
            component: dynamicWrapper(app, ['messageTemplate'], () => import('../routes/MessageTemplate')),
          },
          {
            name: '站点权限配置',
            path: 'station-authority-option',
            isHide: false,
            component: dynamicWrapper(app, ['stationAuthorityOption'], () => import('../routes/StationAuthorityOption')),
          },
          {
            name: '巡视对象配置',
            path: 'patrol-target-config',
            isHide: false,
            component: dynamicWrapper(app, ['patrolTargetConfig'], () => import('../routes/SystemManagement/PatrolTargetConfig')),
          },
          {
            name: '巡视对象配置详情',
            path: 'patrol-target-config-detial',
            isHide: true,
            component: dynamicWrapper(app, ['patrolTargetConfig'], () => import('../routes/SystemManagement/PatrolTargetConfigDetial')),
          },
        ],
      },
    ],
  },
  {
    component: dynamicWrapper(app, [], () => import('../layouts/UserLayout')),
    path: '/user',
    layout: 'UserLayout',
    children: [
      {
        name: '帐户',
        icon: 'user',
        path: 'user',
        isHide: true,
        children: [
          {
            name: '登录',
            path: 'login',
            isHide: true,
            component: dynamicWrapper(app, [], () => import('../routes/User/Login')),
          },
        ],
      },
    ],
  },
  {
    component: dynamicWrapper(app, [], () => import('../layouts/EmerLayout')),
    path: '/emer',
    name: '应急',
    layout: 'EmerLayout',
    children: [
      {
        name: '应急管理',
        icon: 'contacts',
        path: 'emer/emergency',
        component: dynamicWrapper(app, ['emer', 'emerLfMap'], () => import('../routes/emer/index')),
      },
    ],
  },
];
